### ISSUE TITLE
ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by PhilicJone** [LiuLab-Bioelectronics-Harvard/UnitedNet#3]
When I run: model. train (adatas_train, verbose=True), the following error occurs:
>>> model = UnitedNet(root_save_path, device=device, technique=patchseq_config)
>>> model.train(adatas_train,adatas_val = adatas_test)
training
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre2/jdhan_pkuhpc/zhangshiqiang/Sperm/transformer/UnitedNet_NatComm_data/UnitedNet-main/src/interface.py", line 66, in train
    self.model, dataloader_train, dataloader_test,verbose=verbose
  File "/lustre2/jdhan_pkuhpc/zhangshiqiang/Sperm/transformer/UnitedNet_NatComm_data/UnitedNet-main/src/scripts.py", line 369, in run_train
    for schedule in get_schedules_by_task(task, model)
  File "/lustre2/jdhan_pkuhpc/zhangshiqiang/Sperm/transformer/UnitedNet_NatComm_data/UnitedNet-main/src/scripts.py", line 369, in <listcomp>
    for schedule in get_schedules_by_task(task, model)
  File "/lustre2/jdhan_pkuhpc/zhangshiqiang/Sperm/transformer/UnitedNet_NatComm_data/UnitedNet-main/src/scripts.py", line 152, in __init__
    self.optimizer = optim.Adam(self.parameters, lr=model.config[str_lr], )
  File "/lustre2/jdhan_pkuhpc/zhangshiqiang/Software/anaconda2/envs/hicexp/lib/python3.7/site-packages/torch/optim/adam.py", line 137, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/lustre2/jdhan_pkuhpc/zhangshiqiang/Software/anaconda2/envs/hicexp/lib/python3.7/site-packages/torch/optim/optimizer.py", line 61, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list

**Comment by jiangqun19** [comment]
Line 136 of the scripts.py file seems superfluous and can be resolved by deleting it.

**Comment by PhilicJone** [comment]
> Line 136 of the scripts.py file seems superfluous and can be resolved by deleting it.

Do you mean this line？
“ if ((method == str_finetune) and clas_flag) or (method == str_transfer):”？

**Comment by Dingcheng-jie** [comment]
> 
注释这一句：self.optimizer = optim.Adam(self.parameters, lr=model.config[str_lr])

**Comment by jiangqun19** [comment]
@PhilicJone 是优化器多了一个 楼下那个是对的

**Comment by PhilicJone** [comment]
> @PhilicJone 是优化器多了一个 楼下那个是对的

管用了，多谢

**Comment by qpmnh** [comment]
求助数据的读入问题。adatas_train和adatas_test两个变量应该怎么设置

**Comment by qpmnh** [comment]
@PhilicJone @Dingcheng-jie 您知道UnitedNet模型训练部分，怎么读入数据？adatas_train和adatas_test这两个变量很是让人费解。我是搞deep learning的，没有一点生物学的基础，想猜也猜不出来。能否提供一些思路或者分享下数据读入部分的代码。
